sudo: false
language: node_js
node_js: 
  - 10
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - npm install
script:
  - hexo generate
after_success:
  - git config --global user.name "l2m2"
  - git config --global user.email "l2m2lq@gmail.com"
  - cd ./public
  - git init
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force "https://${GH_TOKEN}@github.com/l2m2/l2m2.github.io.git" master:master